name: pnpm
on:
  workflow_call:
    inputs:
      debug:
        type: boolean
        description: "set tmate on failure"
        required: true
      target:
        type: string
        description: "pnpm target"
        required: true
      ref:
        type: string
        description: "checkout specific ref"
        required: true
      all_platform:
        type: boolean
        description: "test on all platforms or not"
        default: false

defaults:
  run:
    shell: bash

jobs:
  make:
    strategy:
      matrix:
        platform: ${{ inputs.all_platform && fromJSON('["ubuntu-latest", "macos-latest", "windows-latest"]') || fromJSON('["ubuntu-latest"]') }}
    runs-on: ${{ matrix.platform }}
    steps:
      - if: ${{ runner.os == 'Windows' }}
        name: Use GNU tar for faster cache restore
        shell: cmd
        run: |
          echo "Adding GNU tar to PATH"
          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: "try to use build cache"
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-${{ inputs.target == 'cache' && github.run_id || hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: pnpm ${{ inputs.target }}
        if: ${{ inputs.target != 'cache' }}
        run: pnpm ${{ inputs.target }}
      - name: "set up tmate session if necessary"
        if: ${{ failure() && inputs.debug }}
        uses: mxschmitt/action-tmate@v3
